name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Check dependencies
        run: |
            go version
            test -z "$(go mod tidy  && git status --porcelain)"
            go mod verify

  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Check build
        run: |
          go version
          pwd && ls -l

          go install go.k6.io/xk6/cmd/xk6@master
          MODULE_NAME=`go list -m`

          GOPRIVATE="go.k6.io/k6" xk6 build \
            --output ./k6ext \
            --with $MODULE_NAME="."
          ./k6ext version
